service: flashcard-generator

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  generateFlashcards:
    handler: src/main/handler.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: generate
          method: post
          cors: true

package:
  include:
    - src/main/handler.py
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**
    - .serverless/**
