name: Deploy to AWS Lambda
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::123260218585:role/flash-cards-deploy-role

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Install dependencies
        run: |
          npm install -g serverless
          npm install

      - name: Deploy to AWS Lambda
        run: |
          serverless deploy

